/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexLayoutRouteImport } from './routes/_indexLayout'
import { Route as IndexLayoutIndexRouteImport } from './routes/_indexLayout/index'
import { Route as IndexLayoutSettingsRouteImport } from './routes/_indexLayout/settings'
import { Route as IndexLayoutDownloadRouteImport } from './routes/_indexLayout/download'
import { Route as IndexLayoutPlaylistTitleRouteImport } from './routes/_indexLayout/playlist.$title'

const IndexLayoutRoute = IndexLayoutRouteImport.update({
  id: '/_indexLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLayoutIndexRoute = IndexLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndexLayoutRoute,
} as any)
const IndexLayoutSettingsRoute = IndexLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => IndexLayoutRoute,
} as any)
const IndexLayoutDownloadRoute = IndexLayoutDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => IndexLayoutRoute,
} as any)
const IndexLayoutPlaylistTitleRoute =
  IndexLayoutPlaylistTitleRouteImport.update({
    id: '/playlist/$title',
    path: '/playlist/$title',
    getParentRoute: () => IndexLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/download': typeof IndexLayoutDownloadRoute
  '/settings': typeof IndexLayoutSettingsRoute
  '/': typeof IndexLayoutIndexRoute
  '/playlist/$title': typeof IndexLayoutPlaylistTitleRoute
}
export interface FileRoutesByTo {
  '/download': typeof IndexLayoutDownloadRoute
  '/settings': typeof IndexLayoutSettingsRoute
  '/': typeof IndexLayoutIndexRoute
  '/playlist/$title': typeof IndexLayoutPlaylistTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_indexLayout': typeof IndexLayoutRouteWithChildren
  '/_indexLayout/download': typeof IndexLayoutDownloadRoute
  '/_indexLayout/settings': typeof IndexLayoutSettingsRoute
  '/_indexLayout/': typeof IndexLayoutIndexRoute
  '/_indexLayout/playlist/$title': typeof IndexLayoutPlaylistTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/download' | '/settings' | '/' | '/playlist/$title'
  fileRoutesByTo: FileRoutesByTo
  to: '/download' | '/settings' | '/' | '/playlist/$title'
  id:
    | '__root__'
    | '/_indexLayout'
    | '/_indexLayout/download'
    | '/_indexLayout/settings'
    | '/_indexLayout/'
    | '/_indexLayout/playlist/$title'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLayoutRoute: typeof IndexLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_indexLayout': {
      id: '/_indexLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_indexLayout/': {
      id: '/_indexLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLayoutIndexRouteImport
      parentRoute: typeof IndexLayoutRoute
    }
    '/_indexLayout/settings': {
      id: '/_indexLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof IndexLayoutSettingsRouteImport
      parentRoute: typeof IndexLayoutRoute
    }
    '/_indexLayout/download': {
      id: '/_indexLayout/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof IndexLayoutDownloadRouteImport
      parentRoute: typeof IndexLayoutRoute
    }
    '/_indexLayout/playlist/$title': {
      id: '/_indexLayout/playlist/$title'
      path: '/playlist/$title'
      fullPath: '/playlist/$title'
      preLoaderRoute: typeof IndexLayoutPlaylistTitleRouteImport
      parentRoute: typeof IndexLayoutRoute
    }
  }
}

interface IndexLayoutRouteChildren {
  IndexLayoutDownloadRoute: typeof IndexLayoutDownloadRoute
  IndexLayoutSettingsRoute: typeof IndexLayoutSettingsRoute
  IndexLayoutIndexRoute: typeof IndexLayoutIndexRoute
  IndexLayoutPlaylistTitleRoute: typeof IndexLayoutPlaylistTitleRoute
}

const IndexLayoutRouteChildren: IndexLayoutRouteChildren = {
  IndexLayoutDownloadRoute: IndexLayoutDownloadRoute,
  IndexLayoutSettingsRoute: IndexLayoutSettingsRoute,
  IndexLayoutIndexRoute: IndexLayoutIndexRoute,
  IndexLayoutPlaylistTitleRoute: IndexLayoutPlaylistTitleRoute,
}

const IndexLayoutRouteWithChildren = IndexLayoutRoute._addFileChildren(
  IndexLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLayoutRoute: IndexLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
