export const PLAYLIST_CODES = {
  ALREADY_EXISTS: 'PLAYLIST_ALREADY_EXISTS',
  CREATED: 'PLAYLIST_CREATED',
  DELETED: 'PLAYLIST_DELETED',
  UNKNOWN: 'PLAYLIST_UNKNOWN_ERROR',
  FAILED_RENAME: 'PLAYLIST_FAILED_RENAME',
  NOT_FOUND: 'PLAYLIST_NOT_FOUND'
} as const

export const SONG_CODES = {
  NOT_FOUND: 'SONG_NOT_FOUND',
  ALREADY_EXISTS: 'SONG_ALREADY_EXISTS',
  CREATED: 'SONG_CREATED'
} as const

export const DOWNLOAD_CODES = {
  COMPLETED: 'DOWNLOAD_COMPLETED',
  FAILED: 'DOWNLOAD_FAILED',
  CANCELLED: 'DOWNLOAD_CANCELLED'
} as const

export type CodesCasesModel =
  | (typeof PLAYLIST_CODES)[keyof typeof PLAYLIST_CODES]
  | (typeof SONG_CODES)[keyof typeof SONG_CODES]
  | (typeof DOWNLOAD_CODES)[keyof typeof DOWNLOAD_CODES]
